runtime: python311  # or python310

entrypoint: gunicorn driverapp.wsgi:application

env_variables:
  SECRET_KEY: "your-django-secret-key"
  DEBUG: "False"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
