runtime: python311  # or python310

entrypoint: gunicorn driverapp.wsgi:application

env_variables:
  SECRET_KEY: "your-django-secret-key"
  DEBUG: "True"

beta_settings:
  cloud_sql_instances: circular-music-463403-p3:us-central:django-db
  
handlers:
  - url: /static
    static_dir: staticfiles/

  - url: /.*
    script: auto
