# Generated by Django 4.2.14 on 2024-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_driverhistory_ridehistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverhistory',
            name='paymentStatus',
            field=models.CharField(max_length=255),
        ),
    ]
