# Generated by Django 4.2.14 on 2024-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_driverhistory_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridehistory',
            name='paymentStatus',
            field=models.CharField(max_length=255),
        ),
    ]
