# Generated by Django 4.2.14 on 2024-08-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_alter_ridehistory_paymentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('status', models.BooleanField()),
                ('destination', models.CharField(max_length=255)),
                ('paymentStatus', models.CharField(max_length=255)),
                ('paymentType', models.CharField(default='CASH', max_length=255)),
                ('paymentAmount', models.IntegerField()),
                ('paidAmount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='driverhistory',
            name='paymentAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridehistory',
            name='paymentAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
