# Generated by Django 4.2.14 on 2024-08-14 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_triphistory_driverhistory_paymentamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverhistory',
            name='paymentAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ridehistory',
            name='paymentAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='paidAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='triphistory',
            name='paymentAmount',
            field=models.FloatField(),
        ),
    ]
