# Generated by Django 4.2.14 on 2024-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_driverhistory_paymentamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triphistory',
            name='destination',
            field=models.JSONField(),
        ),
    ]
