# Generated by Django 4.2.13 on 2024-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_driveronline_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pushToken',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
