# Generated by Django 4.2.13 on 2024-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_connection_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveronline',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
