# Generated by Django 4.2.14 on 2024-08-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_connection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='location',
            field=models.JSONField(),
        ),
    ]
