# Generated by Django 4.2.14 on 2024-08-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_connection_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='paymentStatus',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
