# Generated by Django 4.2.14 on 2024-08-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_connection_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='data_driver',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
