# Generated by Django 4.2.14 on 2024-08-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_connection_data_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='data_driver',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
