# Generated by Django 4.2.14 on 2024-08-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_connection_data_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='data_driver',
        ),
    ]
