# Generated by Django 4.2.14 on 2024-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_connection_data_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveronline',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='driveronline',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
    ]
