# Generated by Django 4.2.14 on 2024-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_driveronline_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveronline',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='driveronline',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=500, null=True),
        ),
    ]
