# Generated by Django 4.2.13 on 2024-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
