# Generated by Django 4.2.13 on 2024-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_riderprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
