# Generated by Django 4.2.14 on 2024-07-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_push_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='user',
            new_name='driver',
        ),
    ]
