# Generated by Django 4.2.14 on 2024-08-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_document_document_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleinfo',
            unique_together={('vehicle_registration_number', 'vehicle_license_number')},
        ),
    ]
