# Generated by Django 4.2.14 on 2024-08-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleinfo',
            unique_together=set(),
        ),
    ]
