# Generated by Django 4.2.13 on 2024-07-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_foodorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='user',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='location',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodorder',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_foodorder_connections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodorder',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_foodorder_connections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodorder',
            name='status',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
