# Generated by Django 4.2.13 on 2024-07-10 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_rename_created_at_foodorder_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
    ]
