# Generated by Django 4.2.13 on 2024-07-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_order_receiver_delete_foodorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='food.restaurant'),
        ),
    ]
