# Generated by Django 4.2.14 on 2024-08-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_order_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='restaurant',
        ),
    ]
