# Generated by Django 4.2.14 on 2024-08-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_foodmenu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to='food.restaurant'),
            preserve_default=False,
        ),
    ]
