# Generated by Django 4.2.14 on 2024-08-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0008_foodmenu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to=settings.AUTH_USER_MODEL),
        ),
    ]
