# Generated by Django 4.2.14 on 2024-08-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_foodmenu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_menu', to='food.restaurant'),
        ),
        migrations.AlterField(
            model_name='image',
            name='border_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
